AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  HW3LF1Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LF1_HW3_CF
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LF1
      Description: 'Lambda function 1 HW3'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::176748515449:role/LF1_HW3_CP2_ROLE'

  LF1LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: 
      - HW3LF1Lambda
    Properties:
      LogGroupName: /aws/lambda/LF1_HW3_CF
